export const shopCategories = [
    { value: "clothing", label: "Clothing & Apparel" },
    { value: "accessories", label: "Accessories" },
    { value: "shoes", label: "Shoes" },
    { value: "bags", label: "Bags" },
    { value: "jewelry", label: "Jewelry" },
    { value: "watches", label: "Watches" },
    { value: "electronics", label: "Electronics" },
    { value: "home", label: "Home & Garden" },
    { value: "beauty", label: "Beauty & Personal Care" },
    { value: "sports", label: "Sports & Outdoors" },
    { value: "toys", label: "Toys & Games" },
    { value: "automotive", label: "Automotive" },
    { value: "books", label: "Books & Magazines" },
    { value: "music", label: "Music & Instruments" },
    { value: "pet-supplies", label: "Pet Supplies" },
    { value: "baby", label: "Baby & Kids" },
    { value: "office", label: "Office Supplies" },
    { value: "health", label: "Health & Wellness" },
    { value: "groceries", label: "Groceries & Gourmet Food" },
    { value: "art", label: "Art & Collectibles" },
    { value: "tools", label: "Tools & Hardware" },
    { value: "furniture", label: "Furniture" },
    { value: "lighting", label: "Lighting & Fixtures" },
    { value: "travel", label: "Travel & Luggage" },
    { value: "handmade", label: "Handmade & Crafts" },
    { value: "gaming", label: "Gaming" }
];
